version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: ls src
      - run:
          name: Run Tests
          command: yarn test
      - run: 
          name: Installing aws client
          command: |
            sudo apt-get update && sudo apt-get install -y python-dev
            sudo curl -O https://bootstrap.pypa.io/get-pip.py
            sudo python get-pip.py
            sudo pip install awscli --upgrade
      - run: yarn run deploy
